services:
- type: web
name: gusdemoapp
env: python
plan: free
buildCommand: "pip install -r requirements.txt"
startCommand: "streamlit run demoappinteractiva.py --server.port $PORT --server.address 0.0.0.0"
